XFastest_Technical_Examination/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/XFastestAdmin', as: 'rails_admin'
  get 'articles/index'
  devise_for :users
  # get 'blogs/index'

  resources :blogs do
    resources :articles
  end

  get 'page/:blog_id/articles', to: 'pages#articles', as: 'blog_articles_page'
  get 'page/:blog_id/article/:article_id', to: 'pages#show', as: 'show_blog_article'

  
  
  root to: "pages#index"
end

XFastest_Technical_Examination/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

XFastest_Technical_Examination/app/models/article.rb
class Article < ApplicationRecord
  acts_as_paranoid

  has_rich_text :action_content

  include AASM

  # validations
  validates :title, presence: true

  # relationships
  belongs_to :user
  belongs_to :blog
  has_one_attached :cover_image


  # instance methods
  aasm(column: 'status', no_direct_assignment: true) do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :draft
    end
  end

end

XFastest_Technical_Examination/app/models/blog.rb
class Blog < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  validates :name, presence: true
  has_many :articles, :dependent => :destroy
end

XFastest_Technical_Examination/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
end

XFastest_Technical_Examination/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    render file: "#{Rails.root}/public/404.html",
                  layout: false,
                  status: 404
  end
end

XFastest_Technical_Examination/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_blog
  before_action :find_article , only: [:edit, :update, :destroy ]

  def index
    @articles = @blog.articles.order(created_at: :desc).includes(:blog)
  end

  def new
    @article = @blog.articles.new
  end

  def show
    
  end

  def create
    @article = @blog.articles.new(article_params)
    @article.user = current_user

    if @article.save
      if params[:publish]
        @article.publish! if params[:publish]
        redirect_to blog_articles_path, notice: '文章已發佈'
      else
        # redirect_to edit_blog_article_path(@blog, @article), notice: '文章已儲存'
        redirect_to blog_articles_path, notice: '文章已儲存'
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
    
    case
    when params[:publish]
      @article.publish!
      redirect_to blog_articles_path, notice: '文章已發佈'
    when params[:unpublish]
      @article.unpublish!
      redirect_to blog_articles_path, notice: '文章已下架'
    else
      redirect_to blog_articles_path, notice: '文章已儲存'
    end
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to blog_articles_path, notice: '文章已刪除'
  end

  private

  def find_blog
    @blog = Blog.find(params[:blog_id])
  end

  def find_article
    @article = @blog.articles.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :action_content, :cover_image)
  end
  
end

XFastest_Technical_Examination/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_blog, only: [:edit, :update, :destroy]


  def index
    @blogs = current_user.blogs.order(created_at: :desc).includes(:articles)
  end

  def new
    @blog = current_user.blogs.new
  end

  def create
    @blog = current_user.blogs.new(blog_params)
    @blog.is_blog_manager = current_user.is_blog_manager
    @blog.is_admin = current_user.is_admin

    if @blog.save
      redirect_to blogs_path, notice: '新增成功'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: '更新成功'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: 'blog 已刪除'
  end

  private
  def find_blog
    @blog = current_user.blogs.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:name)
  end

end

XFastest_Technical_Examination/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_blog, only: [:articles, :show ]

  def index
    @blogs = Blog.where(is_blog_manager: true).order(created_at: :desc).includes(:articles, :user)
  end

  def articles
    @articles = @blog.articles.where(status: 'published').order(created_at: :desc).includes(:blog)
  end

  def show
    @article = @blog.articles.find(params[:article_id])
  end

  private

  def find_blog
    @blog = Blog.find(params[:blog_id])
  end

end

XFastest_Technical_Examination/app/helpers/application_helper.rb
module ApplicationHelper
end

XFastest_Technical_Examination/app/helpers/articles_helper.rb
module ArticlesHelper
end

XFastest_Technical_Examination/app/helpers/blogs_helper.rb
module BlogsHelper
end

XFastest_Technical_Examination/app/helpers/pages_helper.rb
module PagesHelper
end

XFastest_Technical_Examination/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

XFastest_Technical_Examination/app/views/articles/_form.html.erb
<% if article.errors.any? %>
<div class="alert alert-danger" role="alert">
  <%= article.errors.full_messages.to_sentence %>
</div>
<% end %>


<%= form_with(model: [blog, article])  do |form| %>
  <%= image_tag article.cover_image.variant(resize: '1000X800'), style: 'display: block;' if article.cover_image.attached? %>
  <%= form.label :cover_image, '封面圖', class: 'form-label' %>
  <%= form.file_field :cover_image, class: 'form-control mb-2' %>

  <%= form.label :title, '標題', class: 'form-label' %>
  <%= form.text_field :title, class: 'form-control mb-2' %>

  <%= form.label :action_content, '內容', class: 'form-label' %>
  <%= form.rich_text_area :action_content, rows:20, class: 'form-control mb-2 height', style: 'min-height: 15em;' %>

<% if article.published? %>
    <%= form.submit '更新', name: 'save_as_draft', class: 'btn btn-primary' %>
  <% else %>
    <%= form.submit '儲存草稿', name: 'save_as_draft', class: 'btn btn-primary' %>
  <% end %>

  <%= form.submit '發佈文章', name: 'publish', class: 'btn btn-success' if article.may_publish? %>

  <%= form.submit '文章下架', name: 'unpublish', class: 'btn btn-danger' if article.may_unpublish? %>
<% end %>

XFastest_Technical_Examination/app/views/articles/edit.html.erb
<h1>edit article</h1>

<%= render 'form', { blog: @blog, article: @article }%>

XFastest_Technical_Examination/app/views/articles/index.html.erb
<h1 class="mb-3">Articles</h1>

<%= link_to 'new article', new_blog_article_path, class:'btn btn-primary mb-3' %>

<% @articles.each do |article| %>
<div class="container">
  <h2>
    <%= link_to article.title, edit_blog_article_path(@blog, article),  class:'text-dark', style: 'text-decoration: none;' %>
    <%= content_tag :span, 'publish', class: 'btn btn-sm btn-success' if article.published? %>
  </h2>
  <p>
    <%= strip_tags(article.action_content.to_s).truncate(30) %>
  </p>
  <p>
    最後編輯時間: <%= time_ago_in_words(article.updated_at) %>
    <%= link_to edit_blog_article_path(@blog, article), class:'btn btn-secondary' do %>
    <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
    <%= link_to blog_article_path(@blog, article), class:'btn btn-danger', method: 'delete' , data: {confirm: '確定刪除?' } do %>
    <i class="fa-solid fa-trash-can"></i>
    <% end %>
    </p>
  </div>
  <hr>
<% end %>

XFastest_Technical_Examination/app/views/articles/new.html.erb
<h1>new article</h1>

<%= render 'form', { blog: @blog, article: @article }%>

XFastest_Technical_Examination/app/views/blogs/_form.html.erb
<%= form_for(blog) do |form| %>
  <%= form.label :name, class: 'form-label' %>
  <%= form.text_field :name, class: 'form-control mb-2' %>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>

XFastest_Technical_Examination/app/views/blogs/edit.html.erb
<h1>edit blog</h1>

<%= render 'form', blog: @blog %>

XFastest_Technical_Examination/app/views/blogs/index.html.erb
<h1>Blogs List</h1>

<div class="row row-cols-1 row-cols-md-2 g-4">
  <% @blogs.each do |blog| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= blog.name %></h5>
          <p class="card-text">
            最後編輯時間:  <%= time_ago_in_words(blog.updated_at) %>
          </p>
          <%= link_to 'articles', blog_articles_path(blog), class:'btn btn-primary' %>
          <%= link_to edit_blog_path(blog), class:'btn btn-secondary' do %>
          <i class="fa-solid fa-pen-to-square"></i>
          <% end %>
          <%= link_to blog_path(blog), class:'btn btn-danger', method: 'delete' , data:
                {confirm: '確定刪除?' } do %>
          <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

XFastest_Technical_Examination/app/views/blogs/new.html.erb
<h1>new blog</h1>

<%= render 'form', blog: @blog %>

XFastest_Technical_Examination/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XFastestTechnicalExamination</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
  <%= render 'shared/frontend/navbar' %>
  <%= render 'shared/frontend/flash' if notice %>
  <div class="container">
  <%= yield %>
  </div>
  
</body>
</html>

XFastest_Technical_Examination/app/views/pages/articles.html.erb
<h1 class="mb-3">Articles</h1>

<% @articles.each do |article| %>
<div class="container">
  <div class="row justify-content-start">
    <div class="col-2">
    <h2>
      <%= link_to article.title, show_blog_article_path(@blog, article),  class:'text-dark', style: 'text-decoration: none;' %>
    </h2>
    <p>
      <%= strip_tags(article.action_content.to_s).truncate(30) %>
      
    </p>
    <p>
      edited: <%= time_ago_in_words(article.updated_at) %>
    </p>

  
    </div>
    <div class="col-2">
      <%= image_tag article.cover_image.variant(resize: '150X100' ), style: 'display: block;' if article.cover_image.attached?
    %>
    </div>
  </div>




  </div>
  <hr>
<% end %>

XFastest_Technical_Examination/app/views/pages/index.html.erb
<h1>Blogs</h1>

<div class="row row-cols-1 row-cols-md-2 g-4">
  <% @blogs.each do |blog| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= blog.name %></h5>
          <p class="card-text">
            最後編輯時間:  <%= time_ago_in_words(blog.updated_at) %>
          </p>
          <%= link_to 'articles', blog_articles_page_path(blog), class:'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

XFastest_Technical_Examination/app/views/pages/show.html.erb
<div class="row justify-content-center mt-5">
  <div class="card" style="width: 40rem;">
  <%= image_tag @article.cover_image.variant(resize: '1000X800' ), style: 'display: block;' if
    @article.cover_image.attached? %>
    <div class="card-body">
      <h5 class="card-title">
        <%= @article.title %>
      </h5>
      <p class="card-text">
        <%= @article.action_content %>
      </p>
    </div>
  </div>
</div>

XFastest_Technical_Examination/app/views/shared/frontend/_flash.html.erb
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>

XFastest_Technical_Examination/app/views/shared/frontend/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'XFastest', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>

      <ul class="nav nav-pills">
        <div class="d-flex">
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            <%= content_tag :i, '', class: 'fas fa-crown has-text-primary' if current_user.is_blog_manager? %>
            <%= current_user.email %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
            <%= link_to 'new blog', new_blog_path, class: 'dropdown-item' %>
            </li>
            <li>
            <%= link_to 'blog list', blogs_path, class: 'dropdown-item' %>
            </li>
            <li>
            <%= link_to '個人資料', edit_user_registration_path, class: 'dropdown-item' %>
            </li>
            <hr class="dropdown-divider">
            <li>
            <%= link_to '登出', destroy_user_session_path, class: 'dropdown-item' , method: 'delete' , data:
                {confirm: '確定登出?' } %>
            </li>
          </ul>
        </li>
          <% else %>
            <li class="nav-item">
              <%= link_to '註冊', new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '登入' , new_user_session_path, class: 'nav-link text-dark' %>
            </li>
          <% end %>
        </div>
      </ul>
    </div>
  </div>
</nav>